name: aisnippets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  dart_openai: ^6.1.1
  file_picker: ^10.3.10
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  intl: ^0.20.2
  json5: ^0.8.2
  ollama_dart: ^0.3.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  popover: ^0.4.0
  riverpod_annotation: ^4.0.2
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  freezed_annotation:
  json_annotation:
  flutter_tailwind_colors: ^0.0.5
  system_theme: ^3.2.0
  webview_all: ^1.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  riverpod_generator: ^4.0.3
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
