// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListarModelosOllama() {
  return window['go']['ia']['IAOpenRouter']['ListarModelosOllama']();
}

export function PreguntarOllama(arg1, arg2) {
  return window['go']['ia']['IAOpenRouter']['PreguntarOllama'](arg1, arg2);
}

export function PreguntarVariosOllama(arg1, arg2) {
  return window['go']['ia']['IAOpenRouter']['PreguntarVariosOllama'](arg1, arg2);
}

export function SetApiKeyOpenRouter(arg1) {
  return window['go']['ia']['IAOpenRouter']['SetApiKeyOpenRouter'](arg1);
}
