// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SeleccionarYLeerCarpeta() {
  return window['go']['main']['AdministradorArchivos']['SeleccionarYLeerCarpeta']();
}

export function SetContext(arg1) {
  return window['go']['main']['AdministradorArchivos']['SetContext'](arg1);
}
