// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CambiarColorHex() {
  return window['go']['main']['GestorColor']['CambiarColorHex']();
}

export function SetContext(arg1) {
  return window['go']['main']['GestorColor']['SetContext'](arg1);
}
